### ISSUE TITLE
[proposal] rename repository to just `go`

### ISSUE THREAD

**Issue by slimsag** [opentracing/api-go#25]
- before: `import "github.com/opentracing/api-golang/opentracing"`
- after - : `import "github.com/opentracing/go/opentracing"`

motivation:

1. `api-golang` is a mouthful.
1. `api` prefix seems uneeded.
1. `go` is preferred over `golang` from what I've seen in the community.

**Comment by bensigelman** [comment]
I like `api-golang` because the `opentracing` org will likely have non-`api` repos and it helps to distinguish them. I don't mind one way or the other about `api-go` and `api-golang`...

**Comment by slimsag** [comment]
Yeah, that is a totally fair argument. My rebuttal though, would be that it is unlikely we would ever want to create e.g. a `go` `java` `rust` etc. repository with non-API related contents.

I'm not fixed on the change, just curious on hearing everyone's thoughts. I do think `api-go` would be an improvement.

**Comment by yurishkuro** [comment]
I prefer to keep the `api-` prefix. If think we might have other repos in this org, like some reference implementations, or even instrumentation libs. For example, my Python instrumentation, that uses monkey-patching, is dependent only on OTAPI, not on our actual tracing client, so I could see us having repos like `instrumentation-python`.

**Comment by bensigelman** [comment]
`api-go` works for me, though it's not on the top of my list right now. @slimsag, if you want to do the work I'll happily go along with it / approve the PR / etc.

**Comment by slimsag** [comment]
Okay. I'll send a PR for it later today.

P.S. @yurishkuro is that `instrumentation-python` lib available publicly somewhere? I'd like to take a look so I can understand how it plays into `api-python` :).

**Comment by yurishkuro** [comment]
Not yet, but I want to os it, because I think it may contain a piece that we will need for interop with TChannel-python, which is OSS.

**Comment by adriancole** [comment]
I prefer having the actual context in the repo name. This makes people who use a common directory for cloning life far easier (and is a fairly common practice).

ex. opentracing-go and ideally opentracing-api (as the latter would simplify conversations once more folks are making language bindings)
